In [22]:
import pandas as pd

In [23]:
path = '/home/filtheo/Cloud-for-AI/workshop_ml_2025/data/raw/sales_train_validation.csv'
path_2 = '/home/filtheo/Cloud-for-AI/workshop_ml_2025/data/raw/calendar.csv'
main_df = pd.read_csv(path)
calendar_df = pd.read_csv(path_2)

In [24]:
# keep only relevant cols for now
calendar_df = calendar_df[['date', 'd']].drop_duplicates()

In [25]:

conveted_df = main_df.copy()

# focus on foods
conveted_df = conveted_df[conveted_df['cat_id'] == 'FOODS']

# focus on stores
to_drop = ['id', 'item_id', 'dept_id', 'cat_id','state_id']
conveted_df = conveted_df.drop(to_drop, axis = 1)

# aggregate by store
conveted_df = conveted_df.groupby(['store_id']).sum().reset_index()
conveted_df

,store_id,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,CA_1,3239,3137,2008,2258,2032,2407,2693,3962,3418,...,2706,3481,4004,2886,2488,2490,2533,2960,3655,4053
1,CA_2,2193,1921,1289,1540,1278,1494,1785,2385,1827,...,2891,3423,3729,2625,2410,2506,2261,2871,3760,4012
2,CA_3,3446,3535,2701,3064,2761,3340,3455,4068,4324,...,3471,4307,5127,3827,3468,3286,3056,3409,4459,4698
3,CA_4,1223,1269,946,1002,1107,1015,1072,1455,1408,...,1664,1883,1995,1879,1722,1581,1629,1751,1971,2043
4,TX_1,1781,1903,1377,1643,1329,2091,1247,2008,2061,...,2049,2412,2629,2434,2113,1834,1777,1922,2319,2491
5,TX_2,2788,2870,2082,2180,1890,2696,1963,2890,2750,...,2549,2795,3221,2268,2440,2196,2239,2547,2930,2853
6,TX_3,2284,2257,1665,1647,1383,2280,1461,2157,2109,...,2396,2737,2867,2132,2513,2212,2151,2370,2600,2421
7,WI_1,1581,1327,977,935,2,1278,1671,2016,1086,...,2700,3195,3501,2282,2135,2290,2285,2790,3242,3317
8,WI_2,1615,1433,1586,2013,967,1709,1668,2064,1786,...,4836,4175,4157,3206,3282,3005,3078,3419,3751,3659
9,WI_3,3028,3106,2543,2596,1854,3783,3475,4746,4093,...,3420,3599,3267,2612,2377,2232,2308,2665,3240,3107

In [26]:
# Create mapping from d to date
date_mapping = dict(zip(calendar_df['d'], calendar_df['date']))

# Rename columns in conveted_df
conveted_df = conveted_df.rename(columns=date_mapping)
conveted_df

,store_id,2011-01-29,2011-01-30,2011-01-31,2011-02-01,2011-02-02,2011-02-03,2011-02-04,2011-02-05,2011-02-06,...,2016-04-15,2016-04-16,2016-04-17,2016-04-18,2016-04-19,2016-04-20,2016-04-21,2016-04-22,2016-04-23,2016-04-24
0,CA_1,3239,3137,2008,2258,2032,2407,2693,3962,3418,...,2706,3481,4004,2886,2488,2490,2533,2960,3655,4053
1,CA_2,2193,1921,1289,1540,1278,1494,1785,2385,1827,...,2891,3423,3729,2625,2410,2506,2261,2871,3760,4012
2,CA_3,3446,3535,2701,3064,2761,3340,3455,4068,4324,...,3471,4307,5127,3827,3468,3286,3056,3409,4459,4698
3,CA_4,1223,1269,946,1002,1107,1015,1072,1455,1408,...,1664,1883,1995,1879,1722,1581,1629,1751,1971,2043
4,TX_1,1781,1903,1377,1643,1329,2091,1247,2008,2061,...,2049,2412,2629,2434,2113,1834,1777,1922,2319,2491
5,TX_2,2788,2870,2082,2180,1890,2696,1963,2890,2750,...,2549,2795,3221,2268,2440,2196,2239,2547,2930,2853
6,TX_3,2284,2257,1665,1647,1383,2280,1461,2157,2109,...,2396,2737,2867,2132,2513,2212,2151,2370,2600,2421
7,WI_1,1581,1327,977,935,2,1278,1671,2016,1086,...,2700,3195,3501,2282,2135,2290,2285,2790,3242,3317
8,WI_2,1615,1433,1586,2013,967,1709,1668,2064,1786,...,4836,4175,4157,3206,3282,3005,3078,3419,3751,3659
9,WI_3,3028,3106,2543,2596,1854,3783,3475,4746,4093,...,3420,3599,3267,2612,2377,2232,2308,2665,3240,3107

In [27]:
conveted_df = conveted_df.melt(id_vars=['store_id'], var_name='date', value_name='y').rename(columns={'store_id': 'unique_id'})

In [28]:
# keep 2.5 years of data
conveted_df = conveted_df[conveted_df['date'] >= '2013-01-01']

In [29]:
save_path = '/home/filtheo/Cloud-for-AI/workshop_ml_2025/data/converted_df.csv'
conveted_df.to_csv(save_path, index=False)

In [30]:
conveted_df_2 = main_df.copy()

# focus on foods
conveted_df_2 = conveted_df_2[(conveted_df_2['cat_id'] == 'FOODS')]

top_50_food_items = conveted_df_2.groupby(['item_id']).sum(numeric_only=True).sum(axis = 1).sort_values(ascending=False).head(50).index

conveted_df_2 = conveted_df_2[conveted_df_2['item_id'].isin(top_50_food_items)]

# focus on these items only
to_drop = ['id','dept_id', 'cat_id','state_id', 'store_id']
conveted_df_2 = conveted_df_2.drop(to_drop, axis = 1)

# aggregate by store
conveted_df_2 = conveted_df_2.groupby(['item_id']).sum().reset_index()
conveted_df_2

,item_id,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,FOODS_1_085,52,64,45,45,25,56,33,70,25,...,89,110,71,67,80,70,75,109,108,90
1,FOODS_1_218,56,45,48,28,22,47,43,53,35,...,95,149,100,83,89,57,66,95,131,108
2,FOODS_2_128,88,61,84,80,125,71,73,79,60,...,77,76,71,40,61,60,70,62,61,61
3,FOODS_2_197,134,164,89,138,130,180,157,163,135,...,56,77,81,62,49,49,49,47,62,80
4,FOODS_2_276,124,163,104,141,113,166,134,181,175,...,41,68,45,73,61,39,58,46,42,63
5,FOODS_2_360,216,250,154,235,144,242,198,232,127,...,185,175,126,121,133,172,160,155,139,126
6,FOODS_3_007,139,162,155,131,126,206,137,100,133,...,181,30,35,88,57,33,65,57,104,72
7,FOODS_3_030,133,85,54,167,152,181,229,279,145,...,79,115,107,82,77,72,83,78,112,82
8,FOODS_3_080,210,145,137,100,143,169,166,230,177,...,117,140,133,117,77,100,111,105,150,127
9,FOODS_3_090,1046,1036,673,642,531,877,1117,1311,1306,...,672,832,789,486,424,425,422,629,793,592
10,FOODS_3_099,0,0,0,0,0,0,0,0,0,...,86,102,134,94,104,96,66,99,104,128
11,FOODS_3_120,0,0,0,0,0,0,0,0,0,...,248,300,261,284,299,216,227,207,307,322
12,FOODS_3_150,244,295,248,274,203,364,269,355,339,...,116,114,102,86,121,80,54,84,127,96
13,FOODS_3_202,106,113,65,80,75,90,98,133,168,...,186,265,338,195,154,144,146,172,248,270
14,FOODS_3_226,210,168,119,165,116,199,191,235,171,...,208,241,239,187,149,162,164,219,193,176
15,FOODS_3_234,156,133,154,299,115,176,159,234,190,...,117,47,151,76,99,118,117,79,69,68
16,FOODS_3_252,289,273,157,172,132,218,227,363,255,...,271,398,377,259,279,224,249,255,440,287
17,FOODS_3_281,0,0,0,68,46,96,82,128,112,...,112,120,81,71,74,53,61,76,110,100
18,FOODS_3_282,0,0,0,0,0,0,0,0,0,...,176,185,289,192,179,124,111,130,139,224
19,FOODS_3_288,0,0,0,0,0,0,0,0,0,...,171,168,208,142,134,120,143,138,194,218
20,FOODS_3_295,125,122,77,68,59,92,87,136,105,...,60,91,133,126,86,110,73,82,155,115
21,FOODS_3_318,1345,1534,757,1196,749,1064,1187,1745,1367,...,128,185,146,152,99,113,102,167,243,153
22,FOODS_3_319,20,44,40,34,13,26,36,71,46,...,2,0,0,0,0,0,0,0,0,0
23,FOODS_3_329,0,0,0,0,0,0,0,0,0,...,125,149,171,151,163,122,115,112,141,180
24,FOODS_3_376,77,69,63,95,55,88,101,105,76,...,171,152,207,58,59,64,79,86,140,144
25,FOODS_3_377,183,158,95,144,88,133,165,161,115,...,135,139,134,101,131,127,111,132,161,153
26,FOODS_3_389,84,65,49,57,70,71,94,114,116,...,102,130,152,112,101,114,105,95,115,120
27,FOODS_3_412,47,53,53,124,57,64,62,51,50,...,17,43,147,112,52,45,26,62,66,79
28,FOODS_3_458,108,90,80,73,72,87,122,107,120,...,111,117,133,81,99,71,109,99,118,124
29,FOODS_3_462,65,74,53,48,36,83,60,74,53,...,94,133,109,52,63,44,36,62,115,108
30,FOODS_3_491,235,195,200,117,123,170,212,280,224,...,94,137,131,67,83,104,71,101,92,148
31,FOODS_3_498,101,105,63,122,81,209,59,236,191,...,51,57,43,134,60,42,66,42,76,32
32,FOODS_3_501,92,118,83,76,93,94,107,163,190,...,87,95,146,100,81,76,56,70,96,108
33,FOODS_3_541,141,123,119,75,90,72,82,97,155,...,0,0,0,0,0,0,0,0,0,0
34,FOODS_3_547,74,138,158,197,57,143,92,88,110,...,34,83,65,65,66,49,53,35,100,68
35,FOODS_3_555,321,315,214,204,159,265,240,425,355,...,237,315,288,211,230,209,215,247,303,238
36,FOODS_3_586,516,479,328,376,319,430,405,624,537,...,396,481,530,391,434,373,365,381,477,449
37,FOODS_3_587,298,353,234,310,205,214,190,572,508,...,254,242,308,247,214,190,168,242,277,305
38,FOODS_3_607,0,0,0,0,0,0,0,0,0,...,70,120,138,102,52,39,52,73,89,117
39,FOODS_3_635,133,139,127,59,65,77,94,119,142,...,0,0,0,0,0,0,0,0,0,0
40,FOODS_3_681,82,76,58,63,61,80,93,140,142,...,250,280,258,188,169,131,152,246,329,205
41,FOODS_3_694,291,230,187,200,136,234,254,325,251,...,217,256,267,201,183,156,171,189,237,223
42,FOODS_3_711,148,152,102,220,79,237,201,219,131,...,77,48,45,147,79,38,90,55,103,38
43,FOODS_3_714,238,215,141,144,96,139,169,277,219,...,250,286,285,183,153,136,169,205,258,205
44,FOODS_3_723,295,280,169,162,149,280,321,465,434,...,234,265,225,162,132,155,133,215,259,193
45,FOODS_3_752,103,148,232,154,64,93,147,192,149,...,131,148,160,136,159,75,77,57,127,117
46,FOODS_3_764,0,0,0,0,0,0,0,0,0,...,47,64,75,76,69,59,47,42,53,91
47,FOODS_3_804,81,80,47,59,41,85,46,63,69,...,133,148,125,121,129,126,113,176,128,95
48,FOODS_3_808,103,104,114,77,60,73,74,81,123,...,0,2,0,1,0,0,0,0,0,0
49,FOODS_3_811,0,0,0,0,0,0,0,0,0,...,170,170,267,134,143,131,154,186,206,211

In [31]:
# Create mapping from d to date
date_mapping = dict(zip(calendar_df['d'], calendar_df['date']))

# Rename columns in conveted_df
conveted_df_2 = conveted_df_2.rename(columns=date_mapping)
conveted_df_2

,item_id,2011-01-29,2011-01-30,2011-01-31,2011-02-01,2011-02-02,2011-02-03,2011-02-04,2011-02-05,2011-02-06,...,2016-04-15,2016-04-16,2016-04-17,2016-04-18,2016-04-19,2016-04-20,2016-04-21,2016-04-22,2016-04-23,2016-04-24
0,FOODS_1_085,52,64,45,45,25,56,33,70,25,...,89,110,71,67,80,70,75,109,108,90
1,FOODS_1_218,56,45,48,28,22,47,43,53,35,...,95,149,100,83,89,57,66,95,131,108
2,FOODS_2_128,88,61,84,80,125,71,73,79,60,...,77,76,71,40,61,60,70,62,61,61
3,FOODS_2_197,134,164,89,138,130,180,157,163,135,...,56,77,81,62,49,49,49,47,62,80
4,FOODS_2_276,124,163,104,141,113,166,134,181,175,...,41,68,45,73,61,39,58,46,42,63
5,FOODS_2_360,216,250,154,235,144,242,198,232,127,...,185,175,126,121,133,172,160,155,139,126
6,FOODS_3_007,139,162,155,131,126,206,137,100,133,...,181,30,35,88,57,33,65,57,104,72
7,FOODS_3_030,133,85,54,167,152,181,229,279,145,...,79,115,107,82,77,72,83,78,112,82
8,FOODS_3_080,210,145,137,100,143,169,166,230,177,...,117,140,133,117,77,100,111,105,150,127
9,FOODS_3_090,1046,1036,673,642,531,877,1117,1311,1306,...,672,832,789,486,424,425,422,629,793,592
10,FOODS_3_099,0,0,0,0,0,0,0,0,0,...,86,102,134,94,104,96,66,99,104,128
11,FOODS_3_120,0,0,0,0,0,0,0,0,0,...,248,300,261,284,299,216,227,207,307,322
12,FOODS_3_150,244,295,248,274,203,364,269,355,339,...,116,114,102,86,121,80,54,84,127,96
13,FOODS_3_202,106,113,65,80,75,90,98,133,168,...,186,265,338,195,154,144,146,172,248,270
14,FOODS_3_226,210,168,119,165,116,199,191,235,171,...,208,241,239,187,149,162,164,219,193,176
15,FOODS_3_234,156,133,154,299,115,176,159,234,190,...,117,47,151,76,99,118,117,79,69,68
16,FOODS_3_252,289,273,157,172,132,218,227,363,255,...,271,398,377,259,279,224,249,255,440,287
17,FOODS_3_281,0,0,0,68,46,96,82,128,112,...,112,120,81,71,74,53,61,76,110,100
18,FOODS_3_282,0,0,0,0,0,0,0,0,0,...,176,185,289,192,179,124,111,130,139,224
19,FOODS_3_288,0,0,0,0,0,0,0,0,0,...,171,168,208,142,134,120,143,138,194,218
20,FOODS_3_295,125,122,77,68,59,92,87,136,105,...,60,91,133,126,86,110,73,82,155,115
21,FOODS_3_318,1345,1534,757,1196,749,1064,1187,1745,1367,...,128,185,146,152,99,113,102,167,243,153
22,FOODS_3_319,20,44,40,34,13,26,36,71,46,...,2,0,0,0,0,0,0,0,0,0
23,FOODS_3_329,0,0,0,0,0,0,0,0,0,...,125,149,171,151,163,122,115,112,141,180
24,FOODS_3_376,77,69,63,95,55,88,101,105,76,...,171,152,207,58,59,64,79,86,140,144
25,FOODS_3_377,183,158,95,144,88,133,165,161,115,...,135,139,134,101,131,127,111,132,161,153
26,FOODS_3_389,84,65,49,57,70,71,94,114,116,...,102,130,152,112,101,114,105,95,115,120
27,FOODS_3_412,47,53,53,124,57,64,62,51,50,...,17,43,147,112,52,45,26,62,66,79
28,FOODS_3_458,108,90,80,73,72,87,122,107,120,...,111,117,133,81,99,71,109,99,118,124
29,FOODS_3_462,65,74,53,48,36,83,60,74,53,...,94,133,109,52,63,44,36,62,115,108
30,FOODS_3_491,235,195,200,117,123,170,212,280,224,...,94,137,131,67,83,104,71,101,92,148
31,FOODS_3_498,101,105,63,122,81,209,59,236,191,...,51,57,43,134,60,42,66,42,76,32
32,FOODS_3_501,92,118,83,76,93,94,107,163,190,...,87,95,146,100,81,76,56,70,96,108
33,FOODS_3_541,141,123,119,75,90,72,82,97,155,...,0,0,0,0,0,0,0,0,0,0
34,FOODS_3_547,74,138,158,197,57,143,92,88,110,...,34,83,65,65,66,49,53,35,100,68
35,FOODS_3_555,321,315,214,204,159,265,240,425,355,...,237,315,288,211,230,209,215,247,303,238
36,FOODS_3_586,516,479,328,376,319,430,405,624,537,...,396,481,530,391,434,373,365,381,477,449
37,FOODS_3_587,298,353,234,310,205,214,190,572,508,...,254,242,308,247,214,190,168,242,277,305
38,FOODS_3_607,0,0,0,0,0,0,0,0,0,...,70,120,138,102,52,39,52,73,89,117
39,FOODS_3_635,133,139,127,59,65,77,94,119,142,...,0,0,0,0,0,0,0,0,0,0
40,FOODS_3_681,82,76,58,63,61,80,93,140,142,...,250,280,258,188,169,131,152,246,329,205
41,FOODS_3_694,291,230,187,200,136,234,254,325,251,...,217,256,267,201,183,156,171,189,237,223
42,FOODS_3_711,148,152,102,220,79,237,201,219,131,...,77,48,45,147,79,38,90,55,103,38
43,FOODS_3_714,238,215,141,144,96,139,169,277,219,...,250,286,285,183,153,136,169,205,258,205
44,FOODS_3_723,295,280,169,162,149,280,321,465,434,...,234,265,225,162,132,155,133,215,259,193
45,FOODS_3_752,103,148,232,154,64,93,147,192,149,...,131,148,160,136,159,75,77,57,127,117
46,FOODS_3_764,0,0,0,0,0,0,0,0,0,...,47,64,75,76,69,59,47,42,53,91
47,FOODS_3_804,81,80,47,59,41,85,46,63,69,...,133,148,125,121,129,126,113,176,128,95
48,FOODS_3_808,103,104,114,77,60,73,74,81,123,...,0,2,0,1,0,0,0,0,0,0
49,FOODS_3_811,0,0,0,0,0,0,0,0,0,...,170,170,267,134,143,131,154,186,206,211

In [32]:
conveted_df_2 = conveted_df_2.melt(id_vars=['item_id'], var_name='date', value_name='y').rename(columns={'item_id': 'unique_id'})

In [33]:
# keep 2.5 years of data
conveted_df_2 = conveted_df_2[conveted_df_2['date'] >= '2013-01-01']

In [34]:
save_path = '/home/filtheo/Cloud-for-AI/workshop_ml_2025/data/converted_df_2.csv'
conveted_df_2.to_csv(save_path, index=False)